// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oeglazxskygwdygszusv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9lZ2xhenhza3lnd2R5Z3N6dXN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MTI5NjYsImV4cCI6MjA2MjE4ODk2Nn0.aQPi0SCahAKclESg5r7_Mjok0-jNmB69a9yOWOibbo8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);